
#nomoretorchspam Configuration
[glow_crystal]
	#Amount of space between 2 lightsources on the same disk
	#Range: 2 ~ 5
	DISTANCE = 3
	#Dictates the amount of blocks between 2 vertical light disks
	#Range: 2 ~ 10
	HEIGHTDIFF = 5
	#Dictates the amount of vertical disks that provide light
	#Range: 1 ~ 5
	AMOUNTOFDISCS = 3
	#Dictates the radius of light around the main crystal
	#Range: 1 ~ 15
	RADIUSDIFF = 6

